# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb6a6c04c0111353e10c963b7a5cbef1a3203feb1acf8bee1663b4cf2fea3658164fffc9617347e0978c76db1fd1a8dcf651ecb42df238f2e4d8050e2066ac47

test:
  secret_key_base: 6d54786ec78009254db6425abc957e5dc1a5cf86932ad9b1edd78540ab9536b01f669892f34f6390fa257220dd83d25e01ded66a6d252527feb7b7cc2bfdba2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
